import { z } from "zod";

// ── Quiz Generation Schemas ──────────────────────────────────────────
// These schemas force the LLM to return structured JSON via generateObject().
//
// ARUSH: This is interview-critical. Understand every field.
//
// Interview answer:
//   "I use Zod schemas with generateObject() to force the LLM to return
//    structured JSON. The SDK validates the output at runtime — if the LLM
//    returns invalid JSON, it retries automatically. I define question types
//    (MCQ, true/false, open-ended), difficulty levels, and evaluation rubrics
//    as Zod objects."
//
// Break tests:
//   - Remove a required field → generateObject() retries or throws
//   - Change enum values → LLM adapts to new constraints
//   - Make options array min(2) instead of min(4) → fewer MCQ choices

/** A single quiz question generated by the LLM */
export const QuestionSchema = z.object({
  id: z.string().describe("Unique question ID (e.g., q1, q2, q3)"),
  type: z.enum(["mcq", "true_false", "open_ended"]).describe("Question type"),
  question: z.string().describe("The question text"),
  options: z
    .array(z.string())
    .optional()
    .describe("Answer options for MCQ questions (4 options). Omit for open-ended."),
  correctAnswer: z.string().describe("The correct answer (option text for MCQ, 'true'/'false' for T/F, reference answer for open-ended)"),
  explanation: z.string().describe("Brief explanation of why this answer is correct"),
  topic: z.string().describe("Topic/concept this question tests"),
  difficulty: z.enum(["easy", "medium", "hard"]).describe("Question difficulty"),
});

/** Full quiz output from generateObject() */
export const QuizSchema = z.object({
  questions: z.array(QuestionSchema).min(1).max(20),
  totalQuestions: z.number(),
  estimatedTimeMinutes: z.number().describe("Estimated time to complete in minutes"),
  topics: z.array(z.string()).describe("List of topics covered in this quiz"),
});

export type Question = z.infer<typeof QuestionSchema>;
export type Quiz = z.infer<typeof QuizSchema>;

// ── Evaluation Schemas (LLM-as-Judge) ────────────────────────────────
// For open-ended answers, we make a SECOND generateObject() call.
// The LLM scores the student's answer 1-5 and identifies key points.
//
// Interview answer:
//   "For open-ended quiz answers, I use LLM-as-judge. A second
//    generateObject() call evaluates the student's answer against the
//    reference, scoring 1-5 and identifying which key points were
//    covered or missed. This gives nuanced feedback beyond right/wrong."
//
// Why LLM-as-judge?
//   - Regex/keyword matching can't handle rephrased answers
//   - Structured schema forces consistent scoring
//   - In production, calibrate with human-graded examples

/** Evaluation of a single answer */
export const AnswerEvaluationSchema = z.object({
  questionId: z.string(),
  isCorrect: z.boolean().describe("Whether the answer is correct (for MCQ/T-F: exact match; for open-ended: judge decision)"),
  score: z.number().min(0).max(5).describe("Score: 0=no answer, 1=wrong, 2=partially wrong, 3=partially correct, 4=mostly correct, 5=perfect"),
  feedback: z.string().describe("Specific feedback on what was right or wrong"),
  keyPointsCovered: z.array(z.string()).describe("Key concepts the student correctly addressed"),
  keyPointsMissed: z.array(z.string()).describe("Key concepts the student missed or got wrong"),
});

/** Full evaluation result from generateObject() */
export const QuizEvaluationSchema = z.object({
  evaluations: z.array(AnswerEvaluationSchema),
  overallScore: z.number().describe("Total score as percentage (0-100)"),
  totalCorrect: z.number(),
  totalQuestions: z.number(),
  weakTopics: z.array(z.string()).describe("Topics where the student scored poorly"),
  strongTopics: z.array(z.string()).describe("Topics where the student scored well"),
  overallFeedback: z.string().describe("Summary feedback for the student"),
});

export type AnswerEvaluation = z.infer<typeof AnswerEvaluationSchema>;
export type QuizEvaluation = z.infer<typeof QuizEvaluationSchema>;

// ── Request Validation Schemas ───────────────────────────────────────
// These validate the API request body (not LLM output)

export const generateQuizRequestSchema = z.object({
  documentIds: z.array(z.string()).min(1, "Select at least one document"),
  numQuestions: z.number().min(1).max(20).default(5),
  difficulty: z.enum(["easy", "medium", "hard", "mixed"]).default("mixed"),
  questionTypes: z
    .array(z.enum(["mcq", "true_false", "open_ended"]))
    .min(1)
    .default(["mcq", "true_false", "open_ended"]),
});

export const evaluateQuizRequestSchema = z.object({
  quizId: z.string().min(1, "Quiz ID is required"),
  answers: z.array(
    z.object({
      questionId: z.string(),
      answer: z.string(),
    })
  ).min(1, "Submit at least one answer"),
});

export type GenerateQuizRequest = z.infer<typeof generateQuizRequestSchema>;
export type EvaluateQuizRequest = z.infer<typeof evaluateQuizRequestSchema>;
